### ISSUE TITLE
Please help me/us understand by improving the README

### ISSUE THREAD

**Issue by DamienCassou** [CeleritasCelery/emacs-native-shell-complete#12]
Hi,

I have to admit I don't understand what this package is about exactly. Below is some feedback on the README, it might help you improve it.

- The introductory sentence is "Completion in shell buffers using native mechanisms":
  1. What shell buffers are you talking about?  What about `M-x shell`, `M-x ansi-term`, `M-x vterm`, `M-x eshell`?
  2. What do you mean by "native mechanisms"? Are you talking about front-end mechanisms (i.e., the way the completion candidates are displayed to the user) or about back-end mechanisms (i.e., how to find the completion candidates).
  3. How is your work related to `bash-completions` or the `progcomp` shell option?
  3. From what I understand I believe an introductory sentence such as this one would be clearer: "Fetch completion candidates using your shell (e.g., bash or csh) native mechanism and display them in `M-x shell` buffers using Emacs' facilities (e.g., company-mode or `completion-at-point`)".
- The differences between "shell", "term", "console" and "tty" are not obvious for everyone. What about adding some definitions and explanations at the beginning?
- I then suggest some text explaining what this package is *not* doing. For example, "This package doesn't work in eshell, vterm or ansi-term".
- "various CAD tool shells": I have no idea what that is. What about adding a link or examples?
- The part about completion styles is completely obscure to me. I have used shells for quite some time now and never heard of completion styles before. What are `M-*` and `echo`? How are they different from `<tab>`? When I do `M-: (native-complete-get-completion-style)`, I get `bash` which is not one of the three above-mentioned styles.
- Are all these completion styles paragraphs really important for most users or will it just work by default? If the later, I suggest moving the discussion further down on the page so only the advanced users will get to it and so novice users don't get confused too early.

**Comment by CeleritasCelery** [comment]
Thanks for leaving some very helpful feedback. Let me see if I can address your questions and then update the readme with your input.

Let me start with the problem this package solves. `M-x shell` is better then terminal emulators in every way accept for two.

1. No support for interactive programs (curses)
2. tab complete does not give the same candidates as it does in the shell.

This package solves the second problem. When I say "native mechanisms" I mean that you get the exact same completions in `shell-mode` as you do in terminal emulator (you would call that backend). 

> How is your work related to bash-completions or the progcomp shell option?

This uses `progcomp` to generate the candidates (not directly, but it must be enabled). The cool thing about this package is that if you use `bash-completions` all of the new completions are now available in your `shell-mode` shell. There is no need to port those completions to emacs or pcomplete.

> "various CAD tool shells": I have no idea what that is. What about adding a link or examples?

These are just some proprietary shells that I tested it with. I didn't name them because they are available to the public. But I tried to test it on as many shells as I could. 

> The part about completion styles is completely obscure to me. I have used shells for quite some time now and never heard of completion styles before. What are M-* and echo? How are they different from <tab>?

`tab` is not very reliable for getting all candidates all the time. There are many settings that control its behavior (such as whether or not a single tab with complete the common prefix or print all completions). Also in "dumb" terminals (such as `shell-mode`) it will not print the completion if there is only one because it will try to complete in-line instead. You can configure the shells to work around these issues, but I found it was much more reliable to use other mechanisms to get completions. For example in bash if you press `M-*` it will print all completions. But this doesn't work in zsh. There you have to use `C-D`.

> When I do M-: (native-complete-get-completion-style), I get bash which is not one of the three above-mentioned styles.

There are four completions styles. `bash` is one of them.

> Are all these completion styles paragraphs really important for most users or will it just work by default?

It should just work be default. 

Let me know if that help you better understand this package. If so I will make a PR to update the README and you can review it.

**Comment by DamienCassou** [comment]
> Let me start with the problem this package solves. M-x shell is better then terminal emulators in every way accept for two [...] This package solves the second problem. 

I think that's a brilliant introduction! I would add a link (potentially to a section further down in the README) to support your claim. What is better in `M-x shell` than in vterm? And when compared to ansi-term?

You could also drop a sentence or two about eshell.

> I mean that you get the exact same completions in shell-mode as you do in terminal emulator (you would call that backend).

Great. "back-end" is also the [vocabulary used by company-mode](https://company-mode.github.io/).

> This uses progcomp to generate the candidates (not directly, but it must be enabled). The cool thing about this package is that if you use bash-completions all of the new completions are now available in your shell-mode shell. There is no need to port those completions to emacs or pcomplete.

I think this is also a brilliant explanation and it deserves its place in the README along with a link or two to the bash manual.

> tab is not very reliable for getting all candidates all the time [...]

This paragraph also deserves to be in the README in my opinion. Because everything is supposed to work by default, I would move it to the end though.

> There are four completions styles. bash is one of them.

In this case, I think it should be mentioned otherwise this is very confusing.

> Let me know if that help you better understand this package.


I do. Thank you very much for taking the time to write all this and the package.

> If so I will make a PR to update the README and you can review it.

Sure, please ping me.
